name: Auto-merge dependabot updates

on: pull_request_target

permissions:
  contents: write

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'

    steps:
      - run: |
          gh pr review ${{ env.PR_NUMBER }} --comment -b "LGTM!"
          gh pr review ${{ env.PR_NUMBER }} --approve
          gh pr merge ${{ env.PR_NUMBER }} --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
