name: Approve author & dependabot PR

on: pull_request_target

jobs:
  auto-merge:
    timeout-minutes: 5

    runs-on: ubuntu-22.04
    if: github.actor == 'dalisoft' || github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v6
      - run: |
          gh pr review ${{ env.PR_NUMBER }} --comment -b "LGTM!"
          gh pr review ${{ env.PR_NUMBER }} --approve
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
